# Generated by Django 5.2.5 on 2025-08-09 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statuses', '0002_appointmentstatus_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_hour', models.TimeField()),
                ('ailments', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('surgeries', models.TextField(blank=True, null=True)),
                ('reflexology_diagnostics', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('initial_date', models.DateField(blank=True, null=True)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('appointment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('social_benefit', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_detail', models.TextField(blank=True, null=True)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ticket_number', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status_history', models.JSONField(blank=True, default=list)),
                ('appointment_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='statuses.appointmentstatus')),
            ],
        ),
    ]
