# Generated by Django 5.2.5 on 2025-08-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentstatus',
            name='audit_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
